"use client";
import { useState } from "react";
import JSZip from "jszip";
import * as XLSX from "xlsx";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

export function BulkImporter() {
  function done() {}
  const [zip, setZip] = useState<File | null>(null); const [sheet, setSheet] = useState<File | null>(null); const [status, setStatus] = useState("");
  async function run() { if (!zip || !sheet) return; const supabase = createSupabaseBrowserClient(); if (!supabase) return; setStatus("Importando…"); const book = XLSX.read(await sheet.arrayBuffer(), { type: "array" }); const rows = XLSX.utils.sheet_to_json<(string|number)[]>(book.Sheets[book.SheetNames[0]], { header: 1 }).slice(2).filter(row => row[0]); const archive = await JSZip.loadAsync(zip); const images = Object.values(archive.files).filter(file => !file.dir && /\.(png|jpe?g|webp)$/i.test(file.name)).sort((a,b) => a.name.localeCompare(b.name)); let count = 0; for (let i=0; i<Math.min(rows.length,images.length); i++) { const row=rows[i]; const name=String(row[0]); const code=String(row[2]||""); const price=Number(row[4]||0); const slug=`${name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")}-${Date.now()}-${i}`; const {data: product,error}=await supabase.from("products").insert({name,slug,description:"",price,stock:1,code,active:true}).select().single(); if(error||!product) continue; const blob=await images[i].async("blob"); const ext=images[i].name.split(".").pop()||"png"; const path=`${product.id}/principal.${ext}`; const upload=await supabase.storage.from("product-images").upload(path,blob,{contentType:blob.type}); if(!upload.error) await supabase.from("product_images").insert({product_id:product.id,storage_path:path,sort_order:0}); count++; setStatus(`Importando ${count}/${Math.min(rows.length,images.length)}…`); } setStatus(`${count} productos importados.`); done(); }
  return <section className="mx-auto max-w-7xl border-b border-white/10 px-5 py-6 text-white md:px-10"><p className="eyebrow">Importación masiva</p><div className="mt-3 flex flex-wrap items-center gap-3"><input type="file" accept=".zip" onChange={e=>setZip(e.target.files?.[0]||null)} /><input type="file" accept=".xlsx" onChange={e=>setSheet(e.target.files?.[0]||null)} /><button disabled={!zip||!sheet} onClick={run} className="rounded-full bg-rose px-4 py-2 text-sm disabled:opacity-40">Importar ZIP + Excel</button><span className="text-sm text-gold">{status}</span></div></section>;
}
